sudo: false

language: erlang
arch:
 - amd64
 - ppc64le

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

otp_release:
  - 18.0
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.3

after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
